### ISSUE TITLE
Regarding a Reddit post

### ISSUE THREAD

**Issue by bstrie** [rnza0u/blaze#2]
Hello @rnza0u , yesterday a user submitted a link to this repo as a post to the Rust subreddit. That post was later automatically removed by the spam filter for some reason, and the user messaged the moderators of the Rust subreddit to ask why the post was removed, but then deleted their account before an explanation could be provided. Were you the one who submitted the post? If so, on behalf of the moderators I'd like to follow up to inform you that we're just as puzzled as you are, the post seems to have triggered the automatic spam filter, but in a delayed way that makes no sense according to our understanding of how the filtering tools are supposed to work. In any case, we welcome you to make a new Reddit account and resubmit a post that links to this repo (although as a new account it is likely to be automatically filtered again, but you can message the moderators to manually approve the post). However, the comments in that original post mention that Blaze is already used internally as a name for a build system at Google, so I would consider noting that fact (or tweaking the name slightly) if you choose to resubmit it.

**Comment by rnza0u** [comment]
Hello @bstrie !

Yes, I was indeed that user.

I think i understand why the post was marked as banned. I tried to edit my post after receiving too much bad karma and it instantly got deleted. I was told about this thing by a buddy of mine who knows reddit much more that i do.

When it happened, i got upset and i just deleted my account before starting with a fresh new one. But i chose not to publish my post again, because i was kinda afraid to be ranted again.

I think it is actually very difficult to survive on this website when you have a new account...

Anyways, thank you for reaching out to me here, i appreciate it.

BTW i am seriously considering renaming my tool... but after buying a domain name and having already published packages, it's already quite a bit of work. I will wait until i have at least a few users.
